import { Platform, StyleSheet } from "react-native";
import { center, color, rowCenter, tinyCardShadow } from "./tokens";

export const activityRowColor = {
    blue: "#1877f2",
    blueBg: "#e7f0fd",
    textPrimary: "#050505",
    textSecondary: "#65676b",
    divider: "#ced0d4",
    bgComment: "#f0f2f5",
    bgWhite: color.white,
    deleteRed: "#e41e3f",
} as const;

const activity = { avatarMd: 40, avatarSm: 32, radiusMd: 20, radiusSm: 16, xs: 4, sm: 8, md: 12, lg: 16, xl: 18 } as const;
const activityInputBase = { flex: 1, flexDirection: "row" as const, alignItems: "center" as const, height: activity.avatarSm, backgroundColor: activityRowColor.bgComment, borderRadius: activity.radiusMd, borderWidth: 1, borderColor: "transparent", paddingHorizontal: activity.md };

export const activityRowStyles = StyleSheet.create({
    activityContainer: { backgroundColor: activityRowColor.bgWhite, marginVertical: activity.sm - 2, borderRadius: activity.md, ...Platform.select({ ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.1, shadowRadius: 3 }, android: { elevation: 2 } }) },
    postContainer: { marginLeft: activity.sm, marginVertical: activity.sm },
    avatarMd: { width: activity.avatarMd, height: activity.avatarMd, borderRadius: activity.radiusMd },
    avatarSm: { width: activity.avatarSm, height: activity.avatarSm, borderRadius: activity.radiusSm },
    activityBanner: { ...rowCenter, paddingHorizontal: activity.md, paddingTop: activity.md, paddingBottom: activity.sm, borderBottomWidth: 1, borderBottomColor: activityRowColor.bgComment },
    bannerContent: { marginLeft: 10, alignSelf: "flex-start" },
    followBannerAvatar: { width: activity.avatarMd, height: activity.avatarMd, borderRadius: activity.radiusMd, marginLeft: activity.sm },
    bannerText: { fontSize: 15, color: activityRowColor.textPrimary, lineHeight: 20 },
    bannerName: { fontWeight: "600", color: activityRowColor.textPrimary },
    postCard: { backgroundColor: activityRowColor.bgWhite },
    postHeader: { ...rowCenter, paddingHorizontal: activity.md, paddingTop: activity.md, paddingBottom: activity.sm },
    postHeaderContent: { flex: 1, marginLeft: 10, alignSelf: "flex-start" },
    postAuthorName: { fontSize: 15, fontWeight: "600", color: activityRowColor.textPrimary },
    postContent: { fontSize: 15, color: activityRowColor.textPrimary, lineHeight: 22, minHeight: 66, paddingHorizontal: activity.md, paddingBottom: activity.xs + 2 },
    engagementRow: { ...rowCenter, paddingBottom: activity.xs },
    likeBtn: { paddingVertical: activity.xs, paddingLeft: activity.md, borderRadius: activity.xs },
    likeBtnPlaceholder: { width: 60 },
    likeCountBtn: { marginLeft: activity.sm, borderWidth: 1, borderColor: activityRowColor.divider, borderRadius: 10, paddingHorizontal: activity.xs + 2, paddingVertical: 2 },
    likeCountBtnHover: { backgroundColor: activityRowColor.bgComment },
    likeCountText: { fontSize: 13, color: activityRowColor.textSecondary },
    followBtn: { paddingHorizontal: activity.md, paddingVertical: activity.xs + 1, borderRadius: activity.xs - 2, backgroundColor: activityRowColor.blueBg },
    followBtnActive: { backgroundColor: "#e4e6eb" },
    followBtnText: { fontSize: 13, fontWeight: "600", color: activityRowColor.blue },
    followBtnTextActive: { color: activityRowColor.textPrimary },
    deleteBtn: { padding: activity.sm },
    deleteBtnText: { fontSize: 14, color: activityRowColor.textSecondary },
    commentsSection: { backgroundColor: activityRowColor.bgWhite, paddingHorizontal: activity.md, paddingTop: activity.sm, paddingBottom: activity.md, gap: activity.sm },
    commentList: { gap: activity.sm },
    commentRow: { flexDirection: "row", alignItems: "flex-start", gap: activity.sm },
    flexOne: { flex: 1 },
    commentBubbleHoverArea: { width: "100%" },
    commentBubbleRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", width: "100%" },
    commentBubble: { backgroundColor: activityRowColor.bgComment, borderRadius: activity.xl, paddingHorizontal: 10, paddingVertical: activity.xs + 2, alignSelf: "flex-start", flexShrink: 1 },
    commentAuthor: { fontSize: 12, fontWeight: "600", color: activityRowColor.textPrimary },
    commentContent: { fontSize: 14, color: activityRowColor.textPrimary, lineHeight: 19 },
    commentOptionsWrap: { marginLeft: activity.sm, position: "relative" },
    commentOptionsBtn: { marginLeft: activity.sm, paddingHorizontal: activity.xs + 2, paddingVertical: 1, borderRadius: activity.sm, backgroundColor: activityRowColor.bgComment, ...center, minWidth: 24, minHeight: 20 },
    commentOptionsMenu: { position: "absolute", top: 24, right: 0, backgroundColor: activityRowColor.bgWhite, borderRadius: activity.sm, borderWidth: 1, borderColor: activityRowColor.divider, paddingVertical: activity.xs, minWidth: 110, zIndex: 10, ...Platform.select({ ios: { shadowColor: "#000", shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 2 }, android: { elevation: 2 } }) },
    commentOptionsMenuItem: { ...rowCenter, paddingHorizontal: 10, paddingVertical: activity.xs + 2, gap: activity.xs + 2 },
    commentDeleteText: { fontSize: 13, color: activityRowColor.deleteRed, fontWeight: "600" },
    commentActions: { ...rowCenter, marginTop: activity.xs },
    commentDateWrapper: { ...center, marginRight: activity.sm, marginTop: -2 },
    commentLikeBtn: { paddingTop: 3, paddingBottom: 2, paddingRight: activity.xs, borderRadius: 2 },
    commentLikeCountBtn: { marginLeft: 3, borderWidth: 1, borderColor: activityRowColor.divider, borderRadius: activity.sm, paddingHorizontal: activity.xs, paddingVertical: 1, minHeight: 16, ...center },
    commentLikeCountBtnHover: { backgroundColor: activityRowColor.bgComment },
    commentLikeCountText: { fontSize: 11, lineHeight: 11, textAlign: "center", color: activityRowColor.textSecondary },
    commentInputRow: { ...rowCenter, gap: activity.sm, marginTop: activity.xs },
    commentInputWrapper: activityInputBase,
    commentInputWrapperFocused: activityInputBase,
    commentInput: { flex: 1, fontSize: 14, lineHeight: activity.xl, color: activityRowColor.textPrimary, textAlignVertical: "center" },
    commentSendBtn: { marginLeft: activity.xs + 2 },
    commentSendBtnText: { fontSize: 16, color: activityRowColor.blue },
    dateToggleTouch: { alignSelf: "flex-start" },
    dateText: { fontSize: 12, color: activityRowColor.textSecondary, marginTop: 1 },
    modalBody: { flex: 1, backgroundColor: activityRowColor.bgComment },
    modalHeader: { paddingHorizontal: activity.lg, paddingVertical: 14, backgroundColor: activityRowColor.bgWhite, ...rowCenter, justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: activityRowColor.divider },
    modalTitle: { fontSize: activity.xl, fontWeight: "700", color: activityRowColor.textPrimary },
    modalCloseBtn: { paddingHorizontal: activity.md, paddingVertical: activity.xs + 2, borderRadius: activity.xs - 2, backgroundColor: activityRowColor.bgComment },
    modalCloseBtnText: { fontWeight: "600", color: activityRowColor.textPrimary, fontSize: 13 },
    modalScroll: { flex: 1, paddingTop: activity.sm },
    modalUserRow: { backgroundColor: activityRowColor.bgWhite, marginHorizontal: activity.md, marginVertical: activity.xs, borderRadius: 10, ...tinyCardShadow },
    confirmOverlay: { flex: 1, ...center, backgroundColor: "transparent", paddingHorizontal: activity.lg },
    confirmBackdrop: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
    confirmBlur: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
    confirmCard: { width: "100%", maxWidth: 340, backgroundColor: activityRowColor.bgWhite, borderRadius: activity.md, padding: activity.lg, gap: activity.md, ...tinyCardShadow },
    confirmTitle: { fontSize: 17, fontWeight: "700", color: activityRowColor.textPrimary },
    confirmMessage: { fontSize: 14, lineHeight: 20, color: activityRowColor.textSecondary },
    confirmActions: { ...rowCenter, justifyContent: "flex-end", gap: activity.sm },
    confirmCancelBtn: { paddingHorizontal: activity.md, paddingVertical: activity.sm - 1, borderRadius: activity.sm, backgroundColor: activityRowColor.bgComment },
    confirmCancelText: { fontSize: 13, fontWeight: "600", color: activityRowColor.textPrimary },
    confirmDeleteBtn: { paddingHorizontal: activity.md, paddingVertical: activity.sm - 1, borderRadius: activity.sm, backgroundColor: activityRowColor.deleteRed },
    confirmDeleteText: { fontSize: 13, fontWeight: "700", color: activityRowColor.bgWhite },
    confirmBtnDisabled: { opacity: 0.7 },
});
